// src/dev/solverScenariosFullDay.js
// Full-day pattern-set scenarios: complete 7-8 pattern daily multisets
// (non-seasonal formations only), with duplicates and a completed-pattern case.
// Every asserted cell is doubly proven: solver-guaranteed + ground truth,
// AND forced in every solution of an independent exact-cover intersection
// (relaxed model without the crab rule, so the forced set can only shrink).
export const SOLVER_SCENARIOS_FULLDAY = [
  {
    id: 'fullday-8-hieroglyph-x2-seed1',
    name: 'Full day — 8 patterns (HIEROGLYPH x2), seed 1',
    // exact-cover cross-check: 24 solutions, 533 steps
    grid: [
      { x: 4, y: 3, items: { 'Vase': 1 } },
      { x: 2, y: 6, items: { 'Old Bottle': 1 } },
      { x: 3, y: 6, items: { 'Old Bottle': 1 } },
      { x: 1, y: 6, items: { 'Cockle Shell': 1 } },
      { x: 2, y: 7, items: { 'Cockle Shell': 1 } },
      { x: 5, y: 8, items: { 'Wood': 1 } },
      { x: 6, y: 8, items: { 'Wooden Compass': 1 } },
      { x: 4, y: 0, items: { 'Seaweed': 1 } },
      { x: 5, y: 0, items: { 'Seaweed': 1 } },
      { x: 7, y: 0, items: { 'Sea Cucumber': 1 } },
      { x: 8, y: 0, items: { 'Sea Cucumber': 1 } },
      { x: 9, y: 0, items: { 'Pipi': 1 } },
      { x: 0, y: 2, items: { 'Hieroglyph': 1 } },
      { x: 5, y: 4, items: { 'Crab': 1 } },
      { x: 3, y: 4, items: { 'Crab': 1 } },
      { x: 0, y: 6, items: { 'Crab': 1 } },
      { x: 4, y: 8, items: { 'Crab': 1 } },
      { x: 5, y: 7, items: { 'Crab': 1 } },
      { x: 8, y: 8, items: { 'Crab': 1 } },
      { x: 7, y: 9, items: { 'Crab': 1 } },
      { x: 7, y: 7, items: { 'Crab': 1 } },
      { x: 6, y: 5, items: { 'Crab': 1 } },
      { x: 7, y: 5, items: { 'Crab': 1 } },
      { x: 2, y: 0, items: { 'Crab': 1 } },
      { x: 3, y: 1, items: { 'Crab': 1 } },
      { x: 9, y: 1, items: { 'Crab': 1 } },
      { x: 1, y: 2, items: { 'Crab': 1 } },
      { x: 1, y: 0, items: { 'Crab': 1 } },
      { x: 0, y: 3, items: { 'Crab': 1 } },
      { x: 8, y: 5, items: { 'Sand': 1 } },
      { x: 5, y: 6, items: { 'Sand': 1 } },
    ],
    patterns: ['HIEROGLYPH', 'OLD_BOTTLE', 'COCKLE', 'WOODEN_COMPASS', 'CLAM_SHELLS', 'SEAWEED', 'SEA_CUCUMBERS', 'HIEROGLYPH'],
    assertions: [
      { idx: 6, property: 'guaranteed', expected: true, label: 'G1 (idx 6) guaranteed' },
      { idx: 6, property: 'slug', expected: 'sea_cucumber', label: 'G1 slug = sea_cucumber' },
      { idx: 10, property: 'guaranteed', expected: true, label: 'A2 (idx 10) guaranteed' },
      { idx: 10, property: 'slug', expected: 'vase', label: 'A2 slug = vase' },
      { idx: 11, property: 'guaranteed', expected: true, label: 'B2 (idx 11) guaranteed' },
      { idx: 11, property: 'slug', expected: 'vase', label: 'B2 slug = vase' },
      { idx: 35, property: 'guaranteed', expected: true, label: 'F4 (idx 35) guaranteed' },
      { idx: 35, property: 'slug', expected: 'vase', label: 'F4 slug = vase' },
      { idx: 44, property: 'guaranteed', expected: true, label: 'E5 (idx 44) guaranteed' },
      { idx: 44, property: 'slug', expected: 'hieroglyph', label: 'E5 slug = hieroglyph' },
      { idx: 52, property: 'guaranteed', expected: true, label: 'C6 (idx 52) guaranteed' },
      { idx: 52, property: 'slug', expected: 'old_bottle', label: 'C6 slug = old_bottle' },
      { idx: 53, property: 'guaranteed', expected: true, label: 'D6 (idx 53) guaranteed' },
      { idx: 53, property: 'slug', expected: 'old_bottle', label: 'D6 slug = old_bottle' },
      { idx: 87, property: 'guaranteed', expected: true, label: 'H9 (idx 87) guaranteed' },
      { idx: 87, property: 'slug', expected: 'wood', label: 'H9 slug = wood' },
      { idx: 3, property: 'guaranteed', expected: true, label: 'D1 (idx 3) guaranteed' },
      { idx: 3, property: 'slug', expected: 'seaweed', label: 'D1 slug = seaweed' },
      { idx: 15, property: 'guaranteed', expected: true, label: 'F2 (idx 15) guaranteed' },
      { idx: 15, property: 'slug', expected: 'starfish', label: 'F2 slug = starfish' },
    ],
  },
  {
    id: 'fullday-8-hieroglyph-x2-seed2',
    name: 'Full day — 8 patterns (HIEROGLYPH x2), seed 2',
    // exact-cover cross-check: 956 solutions, 18108 steps
    grid: [
      { x: 1, y: 6, items: { 'Vase': 1 } },
      { x: 6, y: 4, items: { 'Old Bottle': 1 } },
      { x: 6, y: 5, items: { 'Old Bottle': 1 } },
      { x: 2, y: 3, items: { 'Cockle Shell': 1 } },
      { x: 3, y: 4, items: { 'Cockle Shell': 1 } },
      { x: 2, y: 1, items: { 'Wood': 1 } },
      { x: 3, y: 3, items: { 'Sea Cucumber': 1 } },
      { x: 4, y: 3, items: { 'Sea Cucumber': 1 } },
      { x: 0, y: 0, items: { 'Vase': 1 } },
      { x: 1, y: 0, items: { 'Vase': 1 } },
      { x: 0, y: 1, items: { 'Hieroglyph': 1 } },
      { x: 0, y: 5, items: { 'Crab': 1 } },
      { x: 2, y: 6, items: { 'Crab': 1 } },
      { x: 1, y: 7, items: { 'Crab': 1 } },
      { x: 1, y: 5, items: { 'Crab': 1 } },
      { x: 4, y: 4, items: { 'Crab': 1 } },
      { x: 7, y: 4, items: { 'Crab': 1 } },
      { x: 2, y: 4, items: { 'Crab': 1 } },
      { x: 2, y: 0, items: { 'Crab': 1 } },
      { x: 3, y: 2, items: { 'Crab': 1 } },
      { x: 4, y: 2, items: { 'Crab': 1 } },
      { x: 6, y: 2, items: { 'Crab': 1 } },
      { x: 8, y: 0, items: { 'Crab': 1 } },
      { x: 5, y: 2, items: { 'Crab': 1 } },
      { x: 0, y: 2, items: { 'Crab': 1 } },
      { x: 8, y: 5, items: { 'Sand': 1 } },
      { x: 1, y: 8, items: { 'Sand': 1 } },
      { x: 6, y: 9, items: { 'Sand': 1 } },
    ],
    patterns: ['HIEROGLYPH', 'OLD_BOTTLE', 'COCKLE', 'WOODEN_COMPASS', 'CLAM_SHELLS', 'SEAWEED', 'SEA_CUCUMBERS', 'HIEROGLYPH'],
    assertions: [
      { idx: 13, property: 'guaranteed', expected: true, label: 'D2 (idx 13) guaranteed' },
      { idx: 13, property: 'slug', expected: 'wooden_compass', label: 'D2 slug = wooden_compass' },
      { idx: 14, property: 'guaranteed', expected: true, label: 'E2 (idx 14) guaranteed' },
      { idx: 14, property: 'slug', expected: 'wood', label: 'E2 slug = wood' },
      { idx: 35, property: 'guaranteed', expected: true, label: 'F4 (idx 35) guaranteed' },
      { idx: 35, property: 'slug', expected: 'sea_cucumber', label: 'F4 slug = sea_cucumber' },
      { idx: 36, property: 'guaranteed', expected: true, label: 'G4 (idx 36) guaranteed' },
      { idx: 36, property: 'slug', expected: 'pipi', label: 'G4 slug = pipi' },
      { idx: 45, property: 'guaranteed', expected: true, label: 'F5 (idx 45) guaranteed' },
      { idx: 45, property: 'slug', expected: 'old_bottle', label: 'F5 slug = old_bottle' },
      { idx: 55, property: 'guaranteed', expected: true, label: 'F6 (idx 55) guaranteed' },
      { idx: 55, property: 'slug', expected: 'old_bottle', label: 'F6 slug = old_bottle' },
      { idx: 60, property: 'guaranteed', expected: true, label: 'A7 (idx 60) guaranteed' },
      { idx: 60, property: 'slug', expected: 'vase', label: 'A7 slug = vase' },
      { idx: 70, property: 'guaranteed', expected: true, label: 'A8 (idx 70) guaranteed' },
      { idx: 70, property: 'slug', expected: 'hieroglyph', label: 'A8 slug = hieroglyph' },
    ],
  },
  {
    id: 'fullday-8-completed-cockle',
    name: 'Full day — 8 patterns, COCKLE completed (pre-commit)',
    // exact-cover cross-check: 26 solutions, 338 steps
    grid: [
      { x: 4, y: 3, items: { 'Vase': 1 } },
      { x: 2, y: 6, items: { 'Old Bottle': 1 } },
      { x: 3, y: 6, items: { 'Old Bottle': 1 } },
      { x: 0, y: 5, items: { 'Cockle Shell': 1 } },
      { x: 1, y: 6, items: { 'Cockle Shell': 1 } },
      { x: 2, y: 7, items: { 'Cockle Shell': 1 } },
      { x: 6, y: 8, items: { 'Wooden Compass': 1 } },
      { x: 7, y: 8, items: { 'Wood': 1 } },
      { x: 6, y: 4, items: { 'Clam Shell': 1 } },
      { x: 7, y: 4, items: { 'Clam Shell': 1 } },
      { x: 6, y: 0, items: { 'Sea Cucumber': 1 } },
      { x: 7, y: 0, items: { 'Sea Cucumber': 1 } },
      { x: 0, y: 1, items: { 'Vase': 1 } },
      { x: 1, y: 1, items: { 'Vase': 1 } },
      { x: 0, y: 2, items: { 'Hieroglyph': 1 } },
      { x: 5, y: 4, items: { 'Crab': 1 } },
      { x: 4, y: 5, items: { 'Crab': 1 } },
      { x: 2, y: 4, items: { 'Crab': 1 } },
      { x: 2, y: 8, items: { 'Crab': 1 } },
      { x: 6, y: 9, items: { 'Crab': 1 } },
      { x: 8, y: 8, items: { 'Crab': 1 } },
      { x: 6, y: 5, items: { 'Crab': 1 } },
      { x: 8, y: 4, items: { 'Crab': 1 } },
      { x: 7, y: 5, items: { 'Crab': 1 } },
      { x: 6, y: 2, items: { 'Crab': 1 } },
      { x: 7, y: 2, items: { 'Crab': 1 } },
      { x: 6, y: 1, items: { 'Crab': 1 } },
      { x: 7, y: 1, items: { 'Crab': 1 } },
      { x: 1, y: 2, items: { 'Crab': 1 } },
      { x: 6, y: 6, items: { 'Sand': 1 } },
      { x: 8, y: 6, items: { 'Sand': 1 } },
    ],
    patterns: ['HIEROGLYPH', 'OLD_BOTTLE', 'COCKLE', 'WOODEN_COMPASS', 'CLAM_SHELLS', 'SEAWEED', 'SEA_CUCUMBERS', 'HIEROGLYPH'],
    completed: ['COCKLE'],
    assertions: [
      { idx: 36, property: 'guaranteed', expected: true, label: 'G4 (idx 36) guaranteed' },
      { idx: 36, property: 'slug', expected: 'clam_shell', label: 'G4 slug = clam_shell' },
      { idx: 37, property: 'guaranteed', expected: true, label: 'H4 (idx 37) guaranteed' },
      { idx: 37, property: 'slug', expected: 'clam_shell', label: 'H4 slug = clam_shell' },
      { idx: 52, property: 'guaranteed', expected: true, label: 'C6 (idx 52) guaranteed' },
      { idx: 52, property: 'slug', expected: 'old_bottle', label: 'C6 slug = old_bottle' },
      { idx: 53, property: 'guaranteed', expected: true, label: 'D6 (idx 53) guaranteed' },
      { idx: 53, property: 'slug', expected: 'old_bottle', label: 'D6 slug = old_bottle' },
      { idx: 85, property: 'guaranteed', expected: true, label: 'F9 (idx 85) guaranteed' },
      { idx: 85, property: 'slug', expected: 'wood', label: 'F9 slug = wood' },
      { idx: 8, property: 'guaranteed', expected: true, label: 'I1 (idx 8) guaranteed' },
    ],
  },
]
